#!/usr/bin/env python3
"""Bootstrap helper for ~/.claude/skill-archetypes.yaml.

Mines ~/.claude/skills/*/SKILL.md + ~/.claude/plugins/cache/*/skills/*/SKILL.md
and emits a draft manifest to stdout, plus an "unmapped skills" report to stderr.

Usage:
  python3 ~/.claude/scripts/bootstrap-skill-archetypes.py > /tmp/draft-manifest.yaml 2>/tmp/unmapped.txt

Manifest entries are TAGGED HEURISTICALLY based on description keywords.
You reviews + curates before committing to ~/.claude/skill-archetypes.yaml.
"""
import re
from pathlib import Path
from sys import stderr

HOME = Path.home()
PERSONAL_DIR = HOME / ".claude" / "skills"
PLUGIN_CACHE = HOME / ".claude" / "plugins" / "cache"

# Keyword -> archetype heuristics (rough; meant to be edited by you)
HEURISTICS = {
    "always-on": ["brainstorm", "plan", "debug", "test", "review", "memory", "thinking",
                  "decision", "documentation", "handoff", "verification"],
    "brand-content": ["copy", "content", "voice", "brand", "carousel", "caption",
                      "humanize", "newsletter", "social", "writing", "seo",
                      "instagram", "video script", "youtube", "essay"],
    "web-app": ["react", "next", "frontend", "ui", "ux", "vue", "svelte", "tailwind",
                "shadcn", "vercel", "supabase", "postgres", "tsx", "css", "design system"],
    "telegram-bot": ["telegram", "bot ", "n8n workflow", "chatbot"],
    "content-pipeline": ["pipeline", "n8n", "apify", "automation", "scrape",
                         "firecrawl", "rclone"],
    "python-cli": ["python", "django", "fastapi", "pytest"],
    "video-pipeline": ["video", "youtube", "reel", "tiktok", "ffmpeg"],
    "infra-config": ["hook", "config", "settings", "carl", "claude code", "rule",
                     "skill creation", "plugin", "mcp"],
}


def parse_frontmatter(text: str) -> dict:
    """Return dict with name + description from SKILL.md frontmatter."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    block = text[4:end]
    result = {}
    for line in block.splitlines():
        m = re.match(r"^(name|description):\s*(.*)$", line)
        if m:
            result[m.group(1)] = m.group(2).strip().strip("'\"")
    return result


def classify(desc: str) -> list:
    """Heuristic-tag a skill description with archetypes."""
    desc_lower = desc.lower()
    matched = []
    for arch, keywords in HEURISTICS.items():
        if any(k in desc_lower for k in keywords):
            matched.append(arch)
    return matched if matched else []


def discover_personal() -> list:
    """Return [(name, description, archetypes), ...] for personal skills."""
    out = []
    if not PERSONAL_DIR.exists():
        return out
    for skill_md in PERSONAL_DIR.glob("*/SKILL.md"):
        fm = parse_frontmatter(skill_md.read_text(errors="ignore"))
        if not fm.get("name"):
            continue
        arch = classify(fm.get("description", ""))
        out.append((fm["name"], fm.get("description", ""), arch))
    return out


def discover_plugins() -> list:
    """Return [(prefixed_name, description, archetypes), ...] for plugin skills."""
    out = []
    if not PLUGIN_CACHE.exists():
        return out
    for skill_md in PLUGIN_CACHE.glob("*/*/*/skills/*/SKILL.md"):
        fm = parse_frontmatter(skill_md.read_text(errors="ignore"))
        if not fm.get("name"):
            continue
        parts = skill_md.parts
        try:
            plugin = parts[parts.index("cache") + 2]
        except (ValueError, IndexError):
            continue
        prefixed = f"{plugin}:{fm['name']}"
        arch = classify(fm.get("description", ""))
        out.append((prefixed, fm.get("description", ""), arch))
    return out


def main() -> None:
    personal = discover_personal()
    plugins = discover_plugins()

    print("# ~/.claude/skill-archetypes.yaml -- DRAFT generated by bootstrap-skill-archetypes.py")
    print("# Review + curate before committing. Heuristic tags below are STARTING POINTS, not authoritative.")
    print(f"# Source: {len(personal)} personal + {len(plugins)} plugin skills discovered")
    print()
    print("# === Personal skills (~/.claude/skills/) ===")
    print()
    for name, _, arch in sorted(personal):
        if arch:
            print(f'"{name}": [{", ".join(arch)}]')

    print()
    print("# === Plugin skills ===")
    print()
    for name, _, arch in sorted(plugins):
        if arch:
            print(f'"{name}": [{", ".join(arch)}]')

    unmapped = [s for s in personal + plugins if not s[2]]
    print(f"\n=== Unmapped skills ({len(unmapped)} total) ===", file=stderr)
    print("# Skills that the heuristic could NOT tag. Review for manual archetypes.", file=stderr)
    for name, desc, _ in sorted(unmapped):
        short = (desc[:80] + "...") if len(desc) > 80 else desc
        print(f"  {name}  -- {short}", file=stderr)


if __name__ == "__main__":
    main()
